# Project Title

BankApp

## Description

Blockchain decentralized banking application user can
create acccount
deposit ethers
withdraw ethers
check balance

## Getting Started
go to remix.ide
copy and paste Project2.sol into contracts section
compile
change deploy network to avalanche testnet
deploy to avalanche testnet
copy the deployment address
paste in project2.js

### Executing program

* How to run the program
* Step-by-step bullets
```
code blocks for commands
```



## Authors

redtibby


## License

This project is licensed under the MIT License